version: 0.0.{build}
image: Visual Studio 2017
before_build:
- cmd: >-
    cd source/external/gitsubmodules/assimp

    mkdir build_dll

    cd build_dll

    cmake -DASSIMP_BUILD_ASSIMP_TOOLS=OFF -DASSIMP_BUILD_TESTS=OFF -G "Visual Studio 15 Win64" ../

    msbuild Assimp.sln


    xcopy /s/e/y code\Debug\*.dll ..\..\..\dll\win64

    rename code\Debug\assimp-vc140-mt.lib assimp.lib

    xcopy /s/e/y code\Debug\assimp.lib ..\..\..\lib\win64


    cd ../

    xcopy /s/e/y include\assimp\* ..\..\include\assimp\

    xcopy /s/e/y build_dll\include\assimp\config.h ..\..\include\assimp\


    cd ../../../../


    mkdir build

    cd build

    cmake -DINNO_PLATFORM_WIN64=ON -G "Visual Studio 15 Win64" ../source

    cmake -DINNO_PLATFORM_WIN64=ON -G "Visual Studio 15 Win64" ../source
build:
  verbosity: minimal
  
clone_script:
- cmd: >-
    git clone -q --branch=%APPVEYOR_REPO_BRANCH% https://github.com/%APPVEYOR_REPO_NAME%.git %APPVEYOR_BUILD_FOLDER%
    cd %APPVEYOR_BUILD_FOLDER%
    git checkout -q %APPVEYOR_REPO_COMMIT%
    git submodule update --init --recursive